Feature/hw2 words game
Shysh-Oleksandr/DKR pull request #7
Opened 2020-12-19 16:55 UTC by Shysh-Oleksandr

Developed the words game

2020-12-20 12:57 UTC, Hozhyi requested changes

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +                break  # If a match is found, aborts the search.
Could you extract a separate function which will look for matching words?

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +        pattern = re.compile(word.replace(WILDCARD, '.'))
Try to construct such pattern, where only vowels will be at the place of wildcard

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +    elif word.lower() not in word_list:
Effectively this is not needed, as regular expressions work with usual words as well

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +            match = pattern.match(w)
Be aware that `match` function return a match also when only part of ward matches

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +        length += hand.get(letter, 0)
You could extract list `values` from hand and calculate their sum

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +                    raise ValueError
You should raise errors only in case of something unexpected. Here it's absolutely expected that user can enter invalid input. Please - remove using try-except from this function

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +                        (key == 'values' and answer.lower() not in value)):
You could just check that `validator in kwargs`, and no loop will be needed

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +    word_score2 = 7 * handlen - 3 * (n - handlen)
```suggestion
    word_score2 = HAND_SIZE * handlen - 3 * (n - handlen)
```

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +    final_score = word_score1 * word_score2
'New folder 3', from creators of 'New folder' and 'New folder 2'

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +        print(f'"{word}" earned {str(get_word_score(word, calculate_handlen(hand)))} points. '
```suggestion
        print(f'"{word}" earned {get_word_score(word, calculate_handlen(hand))} points. '
```

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +              f'Total: {str(total_score)} points\n')
```suggestion
              f'Total: {total_score} points\n')
```

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +              f'Total: {str(total_score)} points\n')
Please - use a separate print() for 1 more empty line. It's hard to read a string with special characters (here and everywhere else)

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +              f'Total: {str(total_score)} points\n')
Here and everywhere else

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +    if to_substitute.lower() == 'yes':
There's no need to call `lower`, as there's no possible value with capital letter

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +        hand = substitute_hand(hand, letter)
As you allow user to enter a capital letter - don't forget to lower it

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +    if to_replay.lower() == 'yes':
There's no need to call lower, as there's no possible value with capital letter

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +    total_list = []
Why do you store each score? As you need only their sum

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +        total_list[-1] = max(total_list[-1], play_hand(hand, word_list))
Are you sure that we need take the biggest value? I thought we need take only score of replayed game

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +        if word == "!!":
I believe it makes sense to declare a separate constant for '!!'

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +    if letter in hand.keys():
You could check this condition before all other operations, so that you won't perform all other operations here which are not needed

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +            not_used_letters.append(consonant)
You could use `set`, that would be easier

2020-12-20 12:57 UTC, Hozhyi commented on Words Game/ps3.py
> +    """
That function quite long, try to achieve it up to 30 lines long

2020-12-24 19:12 UTC, Shysh-Oleksandr commented on Words Game/ps3.py
> +        total_list[-1] = max(total_list[-1], play_hand(hand, word_list))
In the docstrings of the play_game() function was indicated  the following:
* For each hand, ask the user if they would like to replay the hand.
      If the user inputs 'yes', **they will replay the hand and keep 
      the better of the two scores for that hand.** This can only be done once
      during the game. Once the replay option is used, the user should not
      be asked if they want to replay future hands. Replaying the hand does
      not count as one of the total number of hands the user initially
      wanted to play.

So I thought we should take the biggest value.

2020-12-25 13:15 UTC, Hozhyi requested changes

2020-12-25 13:15 UTC, Hozhyi commented on Words Game/ps3.py
> +        match = pattern.search(w)
`search` can find a match even if part of word is matching. Try use `fullmatch` here

2020-12-25 13:15 UTC, Hozhyi commented on Words Game/ps3.py
> +        if bool(match):
```suggestion
        if match:
```

2020-12-25 13:15 UTC, Hozhyi commented on Words Game/ps3.py
> +        return False  # If the word does not exist, returns False.
```suggestion
        if not is_match(word, word_list):
            return False
```

2020-12-25 13:15 UTC, Hozhyi commented on Words Game/ps3.py
> +        return False  # If the word does not exist, returns False.
Just to highlight what I mean in the previous comment

2020-12-25 22:59 UTC, Hozhyi approved these changes

2020-12-26 11:43 UTC, merged